name: Auto Release

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  auto-release:
    uses: attilasomogyi/github-actions-workflows/.github/workflows/auto-release.yml@main
