name: Build Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "README.md"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"

  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "README.md"
      - "CODE_OF_CONDUCT.md"
      - "CHANGELOG.md"

  workflow_dispatch:
    inputs:
      version:
        description: "Version to bump to"
        required: false

jobs:
  build_docs_job:
    runs-on: ubuntu-22.04

    steps:
      - name: Build documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt-get update
          sudo apt-get install -y git rsync python3 pandoc sed
          npm install -g markdownlint-cli
          pip install -U sphinx sphinx-rtd-theme sphinx-copybutton sphinx-toolbox
          git clone --depth 1 "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
          docs_source_pages="docs/source/pages"
          flags="--from gfm --to rst -s -o"
          pandoc CODE_OF_CONDUCT.md $flags $docs_source_pages/code-of-conduct.rst
          pandoc CONTRIBUTING.md $flags $docs_source_pages/contributing.rst
          pandoc README.md $flags $docs_source_pages/readme.rst
          mv CHANGELOG.md CHANGELOG.md.old
          pandoc --from gfm --to gfm CHANGELOG.md.old -s -o CHANGELOG.md --shift-heading-level-by 1
          sed -i '1s/^/# Changelog\n\n/' CHANGELOG.md
          markdownlint --disable MD001 MD013 MD024 MD021 MD041 -f CHANGELOG.md
          pandoc CHANGELOG.md $flags $docs_source_pages/changelog.rst
          make -C docs clean
          make -C docs html
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          docroot=`mktemp -d`
          rsync -av "docs/build/html/" "${docroot}/"
          pushd "${docroot}"
          git init
          git remote add deploy "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git checkout -b gh-pages
          touch .nojekyll
          git add .
          msg="docs: update documents"
          git commit -am "${msg}"
          git push deploy gh-pages --force
        shell: bash
