name: Build Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "README.md"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"

  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "README.md"
      - "CODE_OF_CONDUCT.md"
      - "CHANGELOG.md"

  workflow_dispatch:

jobs:
  build-documentation:
    uses: attilasomogyi/github-actions-workflows/.github/workflows/build-documentation.yml@main
