name: Deploy GitHub Pages

on:
  push:
    branches: ["gh-pages"]

  workflow_dispatch:

jobs:
  deploy-github-pages:
    uses: attilasomogyi/github-actions-workflows/.github/workflows/deploy-github-pages.yml@main
