name: Initialize README

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize README.md
        run: |
          pip install jinja2-cli
          jinja2 --strict -D repository_name=$(basename $GITHUB_REPOSITORY) repository_owner=$GITHUB_REPOSITORY_OWNER .github/workflows/repository-templates/README.md.j2 > README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(readme): initialize readme.md file"
